### ISSUE TITLE
Amex

### ISSUE THREAD

**Issue by qcasey** [PrivSec-dev/banking-apps-compat-report#125]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### App name

Amex

### Link to app

https://play.google.com/store/apps/details?id=com.americanexpress.android.acctsvcs.us

### App version

6.56.1

### Country of the app

United States 

### Build Number

SQ3A.220705.004.2022081800

### Device

- [ ] Pixel 6a
- [X] Pixel 6 Pro
- [ ] Pixel 6
- [ ] Pixel 5a
- [ ] Pixel 5
- [ ] Pixel 4a (5G)
- [ ] Pixel 4a
- [ ] Pixel 4 XL
- [ ] Pixel 4
- [ ] Pixel 3a XL
- [ ] Pixel 3a
- [ ] Pixel 3 XL
- [ ] Pixel 3

### Google Play installed

- [X] Installed
- [ ] Not installed

### Google Play services Network permission revoked?

- [ ] Revoked
- [X] Not revoked
- [ ] I did not have Google Play services installed

### SafetyNet Enforcement

- [ ] Enforced
- [ ] Not enforced
- [X] Unsure

### Native code debugging

- [X] Enabled
- [ ] Disabled

### Stock OS compatibility

- [X] Works
- [ ] Does not work
- [ ] Not tested

### Profile app tested in

- [ ] Main user profile
- [ ] Secondary user profile
- [X] I used a work profile device manager app (Please mention more details about it down below like the app)

### Description of the app's functionality

Used shelter, but I expect this would also work in main profile. Everything works as expected, credit cards, checking account, fingerprint login, e-deposits.

**Comment by akc3n** [comment]
Thanks @qcasey

**Comment by mshxd** [comment]
Not to bring this up again, but it seems that the app doesn't let you register as a trusted device, so if you have 2FA you need to reauthenticate each login attempt

**Comment by mshxd** [comment]
@akc3n It seems that the app doesn't let you register as a trusted device; it throws an error. So if you have 2FA you need to re-authenticate for each login attempt.

**Comment by akc3n** [comment]
> It seems that the app doesn't let you register as a trusted device; it throws an error. So if you have 2FA you need to re-authenticate for each login attempt.

@mshxd thank you for the update and info. I will take a look at this as time permits (hopefully this weekend).

**Comment by mshxd** [comment]
@akc3n np. FWIW, I tried another device and had the same issue, so I don't think it was an isolated instance.

**Comment by akc3n** [comment]
> It seems that the app doesn't let you register as a trusted device; it throws an error. So if you have 2FA you need to re-authenticate for each login attempt.

> tried another device and had the same issue, so I don't think it was an isolated instance

Any chance you may be using a VPN on either one of the devices you tested this app on?

I've posted a guide with possible workaround solutions here:
https://discuss.grapheneos.org/d/8330-app-compatibility-with-grapheneos

Please let me know if any of those workarounds resolve your issue.

**Comment by mshxd** [comment]
@akc3n unfortunately, following these steps did not work. Not on VPN either

**Comment by 0xunusedusername** [comment]
Tested using the Play Store proper instead of through Aurora, didn't work either :(

**Comment by akc3n** [comment]
> Tested using the Play Store proper instead of through Aurora, didn't work either :(

Thank you @0xunusedusername

**Comment by englut** [comment]
Installed on the latest GrapheneOS in Canada. Same issue with not being able to trust my device. Which means I gotta go through 2FA every time I use the app.
