### ISSUE TITLE
Cent Mobile

### ISSUE THREAD

**Issue by empratyush** [PrivSec-dev/banking-apps-compat-report#142]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### App name

Cent Mobile

### Link to app

https://play.google.com/store/apps/details?id=com.infrasofttech.CentralBank

### App version

v6.1

### Country of the app

India

### Build Number

TP1A.220624.021.A1.2022083000

### Device

- [ ] Pixel 6a
- [ ] Pixel 6 Pro
- [ ] Pixel 6
- [ ] Pixel 5a
- [ ] Pixel 5
- [ ] Pixel 4a (5G)
- [X] Pixel 4a
- [ ] Pixel 4 XL
- [X] Pixel 4
- [ ] Pixel 3a XL
- [ ] Pixel 3a
- [ ] Pixel 3 XL
- [ ] Pixel 3

### Google Play installed

- [X] Installed
- [X] Not installed

### Google Play services Network permission revoked?

- [X] Revoked
- [X] Not revoked
- [X] I did not have Google Play services installed

### SafetyNet Enforcement

- [ ] Enforced
- [X] Not enforced
- [ ] Unsure

### Native code debugging

- [X] Enabled
- [X] Disabled

### Stock OS compatibility

- [X] Works
- [ ] Does not work
- [ ] Not tested

### Profile app tested in

- [X] Main user profile
- [ ] Secondary user profile
- [ ] I used a work profile device manager app (Please mention more details about it down below like the app)

### Description of the app's functionality

everything seems to work fine with or without GMS (including payment via qr code/upi).

**Comment by akc3n** [comment]
Thank you @empratyush

**Comment by slashtab** [comment]
This application has been phased out. Playstore link is also outdated and doesn't open any listed application.

It is replaced with **Cent eeZ**[1] application.

I don't have an account with this bank to test and report further.

[1] https://play.google.com/store/apps/details?id=com.centralbank.retail.omni
