### ISSUE TITLE
BCN Mobile banking

### ISSUE THREAD

**Issue by yann2314** [PrivSec-dev/banking-apps-compat-report#145]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### App name

BCN Mobile banking

### Link to app

https://play.google.com/store/apps/details?id=com.bcn.android.mbanking

### App version

v3.5.2.1

### Country of the app

Switzerland

### Build Number

TP1A.220905.004.A1.2022091400

### Device

- [ ] Pixel 6a
- [ ] Pixel 6 Pro
- [X] Pixel 6
- [ ] Pixel 5a
- [ ] Pixel 5
- [ ] Pixel 4a (5G)
- [ ] Pixel 4a
- [ ] Pixel 4 XL
- [ ] Pixel 4
- [ ] Pixel 3a XL
- [ ] Pixel 3a
- [ ] Pixel 3 XL
- [ ] Pixel 3

### Google Play installed

- [X] Installed
- [ ] Not installed

### Google Play services Network permission revoked?

- [ ] Revoked
- [X] Not revoked
- [ ] I did not have Google Play services installed

### SafetyNet Enforcement

- [ ] Enforced
- [ ] Not enforced
- [X] Unsure

### Native code debugging

- [X] Enabled
- [ ] Disabled

### Stock OS compatibility

- [X] Works
- [ ] Does not work
- [ ] Not tested

### Profile app tested in

- [X] Main user profile
- [ ] Secondary user profile
- [ ] I used a work profile device manager app (Please mention more details about it down below like the app)

### Description of the app's functionality

All features works fine (including scanning QC code payments and biometric)

### Are there any extra notes you think users should know about?

A second app CrontoSign (Swiss https://play.google.com/store/apps/details?id=com.cronto.crontosign.swiss) to validate payments by scanning a QC code.

**Comment by yann2314** [comment]
Link to app is https://play.google.com/store/apps/details?id=com.bcn.android.mbanking

**Comment by akc3n** [comment]
Thank you @yann2314
