### ISSUE TITLE
America First Credit Union - AFCU

### ISSUE THREAD

**Issue by Forbo** [PrivSec-dev/banking-apps-compat-report#148]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### App name

AFCU Mobile

### Link to app

https://play.google.com/store/apps/details?id=com.afcu.mobilebanking

### App version

v 8.1.5

### Country of the app

United States

### Build Number

TP1A.220905.004.2022092300

### Device

- [ ] Pixel 6a
- [ ] Pixel 6 Pro
- [ ] Pixel 6
- [ ] Pixel 5a
- [ ] Pixel 5
- [ ] Pixel 4a (5G)
- [X] Pixel 4a
- [ ] Pixel 4 XL
- [ ] Pixel 4
- [ ] Pixel 3a XL
- [ ] Pixel 3a
- [ ] Pixel 3 XL
- [ ] Pixel 3

### Google Play installed

- [ ] Installed
- [X] Not installed

### Google Play services Network permission revoked?

- [ ] Revoked
- [ ] Not revoked
- [X] I did not have Google Play services installed

### SafetyNet Enforcement

- [ ] Enforced
- [ ] Not enforced
- [X] Unsure

### Native code debugging

- [ ] Enabled
- [ ] Disabled

### Stock OS compatibility

- [ ] Works
- [ ] Does not work
- [X] Not tested

### Profile app tested in

- [ ] Main user profile
- [X] Secondary user profile
- [ ] I used a work profile device manager app (Please mention more details about it down below like the app)

### Description of the app's functionality

When first run it mentions that it requires Google Play Services, but near as I can tell all functionality seems to work fine. I don't know if it does any kind of push notifications, as I've never seen one.

**Comment by akc3n** [comment]
Thank you @Forbo 
I'll review your report this evening when I'm home.
