### ISSUE TITLE
Kaspi.kz: works

### ISSUE THREAD

**Issue by khalykbek** [PrivSec-dev/banking-apps-compat-report#149]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### App name

Kaspi.kz

### Link to app

https://play.google.com/store/apps/details?id=kz.kaspi.mobile

### App version

5.7

### Country of the app

Kazakhstan

### Build Number

TP1A.220905.004.A1.2022092300

### Device

- [ ] Pixel 6a
- [ ] Pixel 6 Pro
- [X] Pixel 6
- [ ] Pixel 5a
- [ ] Pixel 5
- [ ] Pixel 4a (5G)
- [ ] Pixel 4a
- [ ] Pixel 4 XL
- [ ] Pixel 4
- [ ] Pixel 3a XL
- [ ] Pixel 3a
- [ ] Pixel 3 XL
- [ ] Pixel 3

### Google Play installed

- [X] Installed
- [ ] Not installed

### Google Play services Network permission revoked?

- [ ] Revoked
- [X] Not revoked
- [ ] I did not have Google Play services installed

### SafetyNet Enforcement

- [ ] Enforced
- [X] Not enforced
- [ ] Unsure

### Native code debugging

- [ ] Enabled
- [X] Disabled

### Stock OS compatibility

- [X] Works
- [ ] Does not work
- [ ] Not tested

### Profile app tested in

- [X] Main user profile
- [X] Secondary user profile
- [ ] I used a work profile device manager app (Please mention more details about it down below like the app)

### Description of the app's functionality

All app features work as intended.

**Comment by akc3n** [comment]
Thank you @khalykbek 
I'll review your report this evening when I'm home.
