### ISSUE TITLE
Santander Brasil (Pessoa Física)

### ISSUE THREAD

**Issue by storopoli** [PrivSec-dev/banking-apps-compat-report#151]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### App name

Santander Brasil

### Link to app

https://play.google.com/store/apps/details?id=com.santander.app

### App version

12.7.2.0

### Country of the app

Brazil

### Build Number

TP1A.220905.004.A1.2022092300

### Device

- [ ] Pixel 6a
- [ ] Pixel 6 Pro
- [X] Pixel 6
- [ ] Pixel 5a
- [ ] Pixel 5
- [ ] Pixel 4a (5G)
- [ ] Pixel 4a
- [ ] Pixel 4 XL
- [ ] Pixel 4
- [ ] Pixel 3a XL
- [ ] Pixel 3a
- [ ] Pixel 3 XL
- [ ] Pixel 3

### Google Play installed

- [X] Installed
- [ ] Not installed

### Google Play services Network permission revoked?

- [ ] Revoked
- [X] Not revoked
- [ ] I did not have Google Play services installed

### SafetyNet Enforcement

- [ ] Enforced
- [X] Not enforced
- [ ] Unsure

### Native code debugging

- [ ] Enabled
- [X] Disabled

### Stock OS compatibility

- [X] Works
- [ ] Does not work
- [ ] Not tested

### Profile app tested in

- [ ] Main user profile
- [X] Secondary user profile
- [ ] I used a work profile device manager app (Please mention more details about it down below like the app)

### Description of the app's functionality

Everything works perfect

**Comment by storopoli** [comment]
This is going to be 3-issue sprint because Santander Brasil has three apps that I use:

- Person Account app (this one)
- Company Account app #153
- Person Credit Card app #152

**Comment by akc3n** [comment]
Thanks @storopoli 
I'll review your report this evening when I'm home

**Comment by storopoli** [comment]
My pleasure, thanks for maintaining this!

**Comment by jonathancross** [comment]
Is this still working for you?
The UK app is failing and I'm trying to debug.

**Comment by leobragatti** [comment]
When I'm trying to use the app it says the device is rooted.  I'm using the Brazilian app

<img width="1080" height="2424" alt="Image" src="https://github.com/user-attachments/assets/0caa35dc-b74e-4d61-a0f1-c3ae80f20a38" />

**Comment by spring-onion** [comment]
@leobragatti It works with secure app spawning disabled. This is a setting found in the owner profile and is currently system-wide, but in the near future it will be turned into a granular, app specific one.

**Comment by Refold3547** [comment]
GrapheneOS version 2026071100 (https://grapheneos.org/releases#2026071100) added the ability to disable the spawn feature on a per-app basis, which resolves this:
`replace secure (exec) spawning feature with a new implementation with improved app compatibility and a per-app toggle replacing the previous global toggle`

I'd suggest noting this directly in the issue so new users can find the fix more easily.

**Comment by leobragatti** [comment]
thanks @spring-onion . I did as you suggested and it's working
