### ISSUE TITLE
Santander Way: App de cartões (Brazil)

### ISSUE THREAD

**Issue by storopoli** [PrivSec-dev/banking-apps-compat-report#152]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### App name

Santander Way: App de cartões

### Link to app

https://play.google.com/store/apps/details?id=br.com.santander.way

### App version

2.38.0

### Country of the app

Brazil

### Build Number

TP1A.220905.004.A1.2022092300

### Device

- [ ] Pixel 6a
- [ ] Pixel 6 Pro
- [X] Pixel 6
- [ ] Pixel 5a
- [ ] Pixel 5
- [ ] Pixel 4a (5G)
- [ ] Pixel 4a
- [ ] Pixel 4 XL
- [ ] Pixel 4
- [ ] Pixel 3a XL
- [ ] Pixel 3a
- [ ] Pixel 3 XL
- [ ] Pixel 3

### Google Play installed

- [X] Installed
- [ ] Not installed

### Google Play services Network permission revoked?

- [ ] Revoked
- [X] Not revoked
- [ ] I did not have Google Play services installed

### SafetyNet Enforcement

- [ ] Enforced
- [X] Not enforced
- [ ] Unsure

### Native code debugging

- [ ] Enabled
- [X] Disabled

### Stock OS compatibility

- [X] Works
- [ ] Does not work
- [ ] Not tested

### Profile app tested in

- [ ] Main user profile
- [X] Secondary user profile
- [ ] I used a work profile device manager app (Please mention more details about it down below like the app)

### Description of the app's functionality

Everything works ok.

**Comment by akc3n** [comment]
Thanks @storopoli 
Will get this done tonight
