### ISSUE TITLE
CommunityAmerica Credit Union - United States

### ISSUE THREAD

**Issue by Foxtrek64** [PrivSec-dev/banking-apps-compat-report#154]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### App name

CACU

### Link to app

https://play.google.com/store/apps/details?id=com.ifs.banking.fiid1454

### App version

2021110011 and earlier

### Country of the app

United States

### Build Number

TP1A.220905.004.2022092300

### Device

- [ ] Pixel 6a
- [ ] Pixel 6 Pro
- [ ] Pixel 6
- [ ] Pixel 5a
- [X] Pixel 5
- [ ] Pixel 4a (5G)
- [ ] Pixel 4a
- [ ] Pixel 4 XL
- [ ] Pixel 4
- [ ] Pixel 3a XL
- [ ] Pixel 3a
- [ ] Pixel 3 XL
- [ ] Pixel 3

### Google Play installed

- [X] Installed
- [ ] Not installed

### Google Play services Network permission revoked?

- [ ] Revoked
- [X] Not revoked
- [ ] I did not have Google Play services installed

### SafetyNet Enforcement

- [ ] Enforced
- [ ] Not enforced
- [X] Unsure

### Native code debugging

- [ ] Enabled
- [X] Disabled

### Stock OS compatibility

- [ ] Works
- [ ] Does not work
- [X] Not tested

### Profile app tested in

- [ ] Main user profile
- [ ] Secondary user profile
- [X] I used a work profile device manager app (Please mention more details about it down below like the app)

### Description of the app's functionality

All functionality is present. Ability to view banking information, transfer money between accounts, apply for loans, and manage scheduled money transfers has been tested and functions exactly as expected and without issue.

Additionally, no performance differences between running on Graphene and running on a stock Samsung S10.

### Are there any extra notes you think users should know about?

I'd be interested to see if this app can function without Google Play.

This is a shorter report, but I'm here to say "it just works."

**Comment by akc3n** [comment]
@Foxtrek64 thank you. Will review/add tonight.
