### ISSUE TITLE
ANZ Australia

### ISSUE THREAD

**Issue by dngray** [PrivSec-dev/banking-apps-compat-report#157]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### App name

ANZ Australia

### Link to app

https://play.google.com/store/apps/details?id=com.anz.android.gomoney

### App version

4.51.0.0188

### Country of the app

Australia

### Build Number

SP2A.220505.008.2022090700

### Device

- [ ] Pixel 6a
- [ ] Pixel 6 Pro
- [ ] Pixel 6
- [ ] Pixel 5a
- [ ] Pixel 5
- [ ] Pixel 4a (5G)
- [ ] Pixel 4a
- [ ] Pixel 4 XL
- [ ] Pixel 4
- [X] Pixel 3a XL
- [ ] Pixel 3a
- [ ] Pixel 3 XL
- [ ] Pixel 3

### Google Play installed

- [ ] Installed
- [X] Not installed

### Google Play services Network permission revoked?

- [ ] Revoked
- [ ] Not revoked
- [X] I did not have Google Play services installed

### SafetyNet Enforcement

- [ ] Enforced
- [X] Not enforced
- [ ] Unsure

### Native code debugging

- [X] Enabled
- [ ] Disabled

### Stock OS compatibility

- [X] Works
- [ ] Does not work
- [ ] Not tested

### Profile app tested in

- [X] Main user profile
- [ ] Secondary user profile
- [ ] I used a work profile device manager app (Please mention more details about it down below like the app)

### Description of the app's functionality

Everything works

**Comment by tommytran732** [comment]
Added, thanks for the report.
