### ISSUE TITLE
Revolut - Mobile Finance

### ISSUE THREAD

**Issue by ledgeri** [PrivSec-dev/banking-apps-compat-report#164]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### App name

Revolut

### Link to app

https://play.google.com/store/apps/details?id=com.revolut.revolut

### App version

8.74.2

### Country of the app

Lithuania

### Build Number

TP1A.221005.002.2022101500

### Device

- [ ] Pixel 6a
- [ ] Pixel 6 Pro
- [X] Pixel 6
- [ ] Pixel 5a
- [ ] Pixel 5
- [ ] Pixel 4a (5G)
- [ ] Pixel 4a
- [ ] Pixel 4 XL
- [ ] Pixel 4
- [ ] Pixel 3a XL
- [ ] Pixel 3a
- [ ] Pixel 3 XL
- [ ] Pixel 3

### Google Play installed

- [ ] Installed
- [X] Not installed

### Google Play services Network permission revoked?

- [ ] Revoked
- [ ] Not revoked
- [X] I did not have Google Play services installed

### SafetyNet Enforcement

- [ ] Enforced
- [X] Not enforced
- [ ] Unsure

### Native code debugging

- [ ] Enabled
- [X] Disabled

### Stock OS compatibility

- [X] Works
- [ ] Does not work
- [ ] Not tested

### Profile app tested in

- [ ] Main user profile
- [X] Secondary user profile
- [ ] I used a work profile device manager app (Please mention more details about it down below like the app)

### Description of the app's functionality

The test was limited to base functionality test: purchasing with app-provided virtual card.
After a sucessfull authentication (within the app, connected online), i was able to use my balance to buy an item online successfully.

### Are there any extra notes you think users should know about?

For the base test it was not needed to do workarounds, but the app should be able to function fully, but that requires full tests!
Issue duplication because the previous  #90 Does not tested with fully vanilla, google-less setup + i am in an other country.

### ADB logcat of the app if necessary

-

**Comment by akc3n** [comment]
@ledgeri thank you for your submission. Appreciate the details added in the description and extra notes.

**Comment by ledgeri** [comment]
> Revolut is not based in Hungary? It's a Lithuanian bank of a UK LLC.

Ohh sorry, I misinterpeted the site basicly: I was in the mindset of the "where X app works", not as "where X app comes from".
Mistake on my part., but my testing extends the previous one in a way, so @akc3n , we need an update of some kind.
@ph00lt0 Thanks for checking!
