### ISSUE TITLE
BNP Paribas

### ISSUE THREAD

**Issue by d4rklynk** [PrivSec-dev/banking-apps-compat-report#165]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### App name

Mes Comptes BNP Paribas

### Link to app

https://play.google.com/store/apps/details?id=net.bnpparibas.mescomptes&gl=FR

### App version

v4.47.0

### Country of the app

France

### Build Number

TP1A.221005.003.2022101600

### Device

- [X] Pixel 6a
- [ ] Pixel 6 Pro
- [ ] Pixel 6
- [ ] Pixel 5a
- [ ] Pixel 5
- [ ] Pixel 4a (5G)
- [ ] Pixel 4a
- [ ] Pixel 4 XL
- [ ] Pixel 4
- [ ] Pixel 3a XL
- [ ] Pixel 3a
- [ ] Pixel 3 XL
- [ ] Pixel 3

### Google Play installed

- [X] Installed
- [ ] Not installed

### Google Play services Network permission revoked?

- [ ] Revoked
- [X] Not revoked
- [ ] I did not have Google Play services installed

### SafetyNet Enforcement

- [ ] Enforced
- [ ] Not enforced
- [x] Unsure

### Native code debugging

- [ ] Enabled
- [X] Disabled

### Stock OS compatibility

- [X] Works
- [ ] Does not work
- [ ] Not tested

### Profile app tested in

- [ ] Main user profile
- [X] Secondary user profile
- [ ] I used a work profile device manager app (Please mention more details about it down below like the app)

### Description of the app's functionality

Everything works as far as I tested. 
P.S.  I'm not sure about Paylib but it should works

**Comment by tommytran732** [comment]
Added
