### ISSUE TITLE
Service CU Mobile Banking - United States

### ISSUE THREAD

**Issue by gbkelley** [PrivSec-dev/banking-apps-compat-report#166]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### App name

Service CU Mobile Banking

### Link to app

https://play.google.com/store/apps/details?id=com.ifs.mobilebanking.fiid9094&hl=en

### App version

2021.11.00

### Country of the app

US

### Build Number

TP1A.221005.002.2022101800

### Device

- [ ] Pixel 6a
- [ ] Pixel 6 Pro
- [ ] Pixel 6
- [ ] Pixel 5a
- [ ] Pixel 5
- [ ] Pixel 4a (5G)
- [ ] Pixel 4a
- [X] Pixel 4 XL
- [ ] Pixel 4
- [ ] Pixel 3a XL
- [ ] Pixel 3a
- [ ] Pixel 3 XL
- [ ] Pixel 3

### Google Play installed

- [X] Installed
- [ ] Not installed

### Google Play services Network permission revoked?

- [X] Revoked
- [ ] Not revoked
- [ ] I did not have Google Play services installed

### SafetyNet Enforcement

- [ ] Enforced
- [ ] Not enforced
- [X] Unsure

### Native code debugging

- [ ] Enabled
- [X] Disabled

### Stock OS compatibility

- [X] Works
- [ ] Does not work
- [ ] Not tested

### Profile app tested in

- [X] Main user profile
- [ ] Secondary user profile
- [ ] I used a work profile device manager app (Please mention more details about it down below like the app)

### Description of the app's functionality

Logs in gets data and changes data.

**Comment by akc3n** [comment]
Thank you @gbkelley
Will get this taken care of in the morning. 
Much appreciated.
