### ISSUE TITLE
Change listing of ASN Bank, De Volksbank (Netherlands)

### ISSUE THREAD

**Issue by ph00lt0** [PrivSec-dev/banking-apps-compat-report#299]
ASN Bank is part of The Volksbank (https://www.devolksbank.nl/en/banking)

Change ASN Bank to: ASN Bank (De Volksbank)
- https://play.google.com/store/apps/details?id=nl.devolksbank.asn.bankieren
- https://play.google.com/store/apps/details?id=nl.asnbank.mobielbetalen  (Android Pay component)

N.B. first link changed, as currently points to the old app search result.

Suggesting to add:
SNS Bank  (De Volksbank)
- https://play.google.com/store/apps/details?id=nl.devolksbank.sns.bankieren
- https://play.google.com/store/apps/details?id=nl.snsbank.mobielbetalen (Android Pay component)

Regio Bank (De Volksbank)
- https://play.google.com/store/apps/details?id=nl.devolksbank.regio.bankieren
- https://play.google.com/store/apps/details?id=nl.regiobank.mobielbetalen (Android Pay component)

They use the exact same app just different branding.

**Comment by akc3n** [comment]
Thanks @ph00lt0, I had that [noted as a `FIXME` comment](https://github.com/PrivSec-dev/privsec.dev/blob/76c80e1cc22e86a8a1414561bc872518580f0849/content/posts/android/Banking%20Applications%20compatibility%20with%20GrapheneOS.md?plain=1#L247) a long time ago. Appreciate you issuing a correction for this entry.

![image](https://github.com/PrivSec-dev/banking-apps-compat-report/assets/71854332/9f433fa0-4075-4ec6-bcf7-18b1bed9160d)

**Comment by akc3n** [comment]
@ph00lt0 if you have a chance, may you please review the above PR I made with the corrections you issued. Thank you.
