### ISSUE TITLE
ING DiBa Banking App not working

### ISSUE THREAD

**Issue by Earthling-Z3R0** [PrivSec-dev/banking-apps-compat-report#37]
Can't log in. App freezes for a long time, then becomes responsive again bringing you back to login screen. But it will never let you log in.

Tested on Pixel4a running GrapheneOS.

Link to app in Play Store: https://play.google.com/store/apps/details?id=de.ingdiba.bankingapp

**Comment by Zanthed** [comment]
Is this a new app report or an already existing one?

**Comment by Earthling-Z3R0** [comment]
Afaik a new one.

**Comment by Zanthed** [comment]
Okay thank you.

**Comment by akc3n** [comment]
Duplicate #48
