### ISSUE TITLE
BankID Pixel 7 Pro endless loop

### ISSUE THREAD

**Issue by zt3ph4n** [PrivSec-dev/banking-apps-compat-report#488]
When BankID installed and a id attached to it , you're supposed to scan a QR-codes at certain logins/identify's , thou when scanned it just goes into endless loop using latest updates and play store updates installed and it doesn't spit out any error-message, just an endless loop. Atm im not able to attach logs, so i'll add it later, but for the time being, i'm adding this with the edit-option ofc.

Thanks in advance!

**Comment by spring-onion** [comment]
Which one do you mean? Please post your experience in the respective issue:

#8 
#255
