### ISSUE TITLE
Chase Mobile

### ISSUE THREAD

**Issue by galt001** [PrivSec-dev/banking-apps-compat-report#57]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### App name

Chase Mobile

### Link to app

https://play.google.com/store/apps/details?id=com.chase.sig.android

### App version

4.281

### Country of the app

United States

### Device

- [ ] Pixel 6 Pro
- [ ] Pixel 6
- [ ] Pixel 5a
- [ ] Pixel 5
- [ ] Pixel 4a (5G)
- [X] Pixel 4a
- [ ] Pixel 4 XL
- [ ] Pixel 4
- [ ] Pixel 3a XL
- [ ] Pixel 3a
- [ ] Pixel 3 XL
- [ ] Pixel 3

### Google Play installed

- [X] Installed
- [ ] Not installed

### Google Play services Network permission revoked?

- [ ] Revoked
- [X] Not revoked
- [ ] I did not have Google Play services installed

### SafetyNet Enforcement

- [ ] Enforced
- [ ] Not enforced
- [X] Unsure

### Native code debugging

- [X] Enabled
- [ ] Disabled

### Stock OS compatibility

- [X] Works
- [ ] Does not work
- [ ] Not tested

### Profile app tested in

- [X] Main user profile
- [X] Secondary user profile
- [ ] I used a work profile device manager app (Please mention more details about it down below like the app)

### Description of the app's functionality

Chase for my credit cards. don't use the banking function

### Are there any extra notes you think users should know about?

When I installed on my main profile (I deleted my work profile, or essentially moved it to main). I could not get past the verification stage. The screen was flashing and preventing me from entering a verification code. Reboot the phone and try again. It all worked

**Comment by akc3n** [comment]
Chase mobile already submitted #13 
Closing #57
